[package]
name = "sumo-cli-client"
version = "0.1.0"
authors = ["David Carlton <carlton@sumologic.com>"]

[dependencies]
# hyper depends on a version of cookie that isn't newest,
# so pin those two.
cookie = "0.1.*"
hyper = "0.6.*"
getopts = "*"
rpassword = "*"
rustc-serialize = "*"
time = "*"
